### ISSUE TITLE
Prevent unintentionally marking all diffs as done / not done

### ISSUE THREAD

**Issue by sfc-gh-lmoll** [MarcinZukowski/review-pal#2]
When I invested some time to review selected diffs and mark them accordingly I would be really sad if I lost this information by unintentionally clicking once on `clear all` instead of `>`(fold all files).
To prevent this it would help if a double click was necessary or even some sort of dialog asking:
> Do you really want to clear all diffs?

**Comment by MarcinZukowski** [comment]
Done. I added a confirmation for global-change actions in 7c70f2abce1108976ae6f9f4e5fa8595ebb4bca0
