### ISSUE TITLE
Improve searching for selected strings

### ISSUE THREAD

**Issue by sfc-gh-lmoll** [MarcinZukowski/review-pal#3]
Say I see a call of a new function and I quickly want to check what this new function does I typically:
- double click the function to select the string
- copy it via key stroke
- search via browser

Now double clicking a string will highlight all repetitions of it. But it will make the selection disappear.
There is a workaround: Double clicking the string but not releasing after the second click and then copying via key stroke.
But it would help if this workaround wasn't necesseray.

Some ideas of mitigation:
- keeping the selection of a word after double click
- adding some icon in the list of highlighted words in the toolbar to search for this word
- providing a key short cut to search for the last highlighted word

**Comment by MarcinZukowski** [comment]
Interesting. I think selection disappears because we modify DOM to highlight the text. Will think if there's a way to reintroduce the selection.

Another option is to add "find-next" for the highlighted words. I added it in ca2e6db1265a73a39005dc1de12d066ab522d607 in a branch. Take a look, maybe you'll like it this way.

**Comment by sfc-gh-lmoll** [comment]
I pulled and am on `36da6d09` now, but I do not see a difference yet. Tried to reinstall the plugin already.
Is it maybe some new shortcut?

**Comment by MarcinZukowski** [comment]
See the README in the branch https://github.com/MarcinZukowski/review-pal/tree/find-next-selection

Middle-click on the word in the box takes you to the next occurrence

**Comment by sfc-gh-lmoll** [comment]
thanks, works fine! 👍  I also like that the index of the found element is displayed (`5/7`).
Would be cool to have a way of jumping backwards too, but that would be the icing on the cake :)

**Comment by MarcinZukowski** [comment]
Just added backward search, closing this one for now.
